version: '3'
services:
  backend:
    build:
      context: ./backend # Path to the backend project directory
    # depends_on:
    #   - mysql
    ports:
      - 8000:8000
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=school_management_dev
      - DB_USERNAME=root
      - DB_PASSWORD= # This should match MYSQL_ROOT_PASSWORD in MySQL service
    depends_on:
      - mysql
    container_name: backend

  frontend:
    build:
      context: ./frontend # Path to the frontend project directory
    ports:
      - 8080:8080
    container_name: frontend

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=school_management_dev
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysql

volumes:
  db_data: